receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  debug:
    verbosity: detailed

  # otlp/jaeger:
  #   endpoint: jaeger:4317 # OTLP-приемник Jaeger
  #   tls:
  #     insecure: true
  otlphttp/seq-traces:
    endpoint: http://seq:5341/ingest/otlp/v1/traces
    headers:
      Content-Type: application/x-protobuf

  otlphttp/seq-logs:
    endpoint: http://seq:5341
    headers:
      # Content-Type: application/x-protobuf
      Content-Type: application/vnd.serilog.clef

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/seq-traces, debug]
    # traces:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [otlp/jaeger, debug]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/seq-logs, debug]

    # send_batch_size: 1000
    # timeout: 10s
