name: LlamaFly-observability

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.121.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml

  prometheus:
    image: bitnami/prometheus:2.55.1
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-remote-write-receiver"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  loki:
    image: grafana/loki:2.9.13
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/var/loki

  tempo:
    image: grafana/tempo:main-b4769e4
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo_data:/var/tempo

  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=tempoSearch,tempoBackendSearch
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
      - tempo

volumes:
  loki_data:
  prometheus_data:
  tempo_data:
  grafana_data:

    # - GF_FEATURE_TOGGLES_ENABLE=tempoSearch tempoBackendSearch
